import org.jetbrains.kotlin.gradle.dsl.JvmTarget

project.setDescription("This module contains the Kotlin API implemetantion code for building, training, and evaluating the Deep Learning models.")

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'com.android.kotlin.multiplatform.library'

kotlin {
    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }
    android {
        namespace = 'org.jetbrains.kotlinx.dl.impl'
        compileSdk = 36
        minSdk = 24

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                api project(':api')
            }
        }
        jvmMain {
            dependencies {
                api 'com.github.doyaaaaaken:kotlin-csv-jvm:0.7.3' // for csv parsing
                api 'io.github.microutils:kotlin-logging:2.1.21' // for logging
                api 'io.jhdf:jhdf:0.5.7' // for hdf5 parsing
                api 'com.beust:klaxon:5.5'
                implementation 'com.twelvemonkeys.imageio:imageio-jpeg:3.8.2'
            }
        }
        jvmTest {
            dependencies {
                implementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
                implementation 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
                implementation 'org.junit.jupiter:junit-jupiter-params:5.11.4'
                runtimeOnly 'org.junit.platform:junit-platform-launcher'
            }
        }
        androidMain {
            dependencies {
                api 'androidx.camera:camera-core:1.6.1'
            }
        }
    }
    explicitApiWarning()
}

tasks.named('jvmTest') {
    useJUnitPlatform()
}
