pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'KotlinDL'
include("api")
include("impl")
include("tensorflow")
include("visualization")
include("examples")
include("dataset")
include("onnx")
include("gradlePlugin")
