import org.jetbrains.kotlin.gradle.dsl.JvmTarget

project.setDescription("A KotlinDL library provides Dataset API for better Kotlin programming for Deep Learning.")

apply plugin: 'org.jetbrains.kotlin.multiplatform'

kotlin {
    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }
    sourceSets {
        jvmMain {
            dependencies {
                api project(':api')
                api project(':impl')
            }
        }
    }
    explicitApiWarning()
}
