import org.jetbrains.kotlin.gradle.dsl.JvmTarget

repositories {
    gradlePluginPortal()
}

apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'java-gradle-plugin'
apply plugin: 'maven-publish'
apply plugin: 'com.gradle.plugin-publish'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation gradleApi()
    implementation "de.undercouch.download:de.undercouch.download.gradle.plugin:5.7.0"
    implementation "com.android.tools.build:gradle:9.3.1"
}

gradlePlugin {
    website = 'https://github.com/Kotlin/kotlindl'
    vcsUrl = 'https://github.com/Kotlin/kotlindl'
    plugins {
        kotlinDlGradlePlugin {
            id = 'org.jetbrains.kotlinx.kotlin-deeplearning-gradle-plugin'
            implementationClass = 'org.jetbrains.kotlinx.dl.gradle.DownloadModelsPlugin'
            displayName = 'KotlinDL Gradle Plugin'
            description = 'Adds a task for downloading Kotlin DL pretrained models from the model hub'
            tags = ['kotlin', 'deep-learning']
        }
    }
}
