import org.jetbrains.kotlin.gradle.dsl.JvmTarget

project.setDescription("This module contains the Kotlin API for building, training, and evaluating TensorFlow models.")

apply plugin: 'org.jetbrains.kotlin.jvm'

dependencies {
    api project(":dataset")
    api project(":api")
    api project(":impl")
    api 'org.tensorflow:tensorflow:1.15.0'
    api 'org.tensorflow:proto:1.15.0'
    api 'com.google.protobuf:protobuf-java:3.21.9'
    api 'com.beust:klaxon:5.5'
    api 'io.github.microutils:kotlin-logging:2.1.21' // for logging

    testImplementation 'ch.qos.logback:logback-classic:1.5.18'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
    explicitApiWarning()
}

tasks.named('test') {
    useJUnitPlatform()
}

apply from: project.rootProject.file('gradle/tensorflowTestJvm.gradle')

tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}
