import org.jetbrains.kotlin.gradle.dsl.JvmTarget

project.setDescription("This module contains the Kotlin API for loading and executing the ONNX models.")

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'com.android.kotlin.multiplatform.library'

kotlin {
    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }
    android {
        namespace = 'org.jetbrains.kotlinx.dl.onnx'
        compileSdk = 36
        minSdk = 24

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                api project(":api")
                api project(":impl")
            }
        }
        jvmMain {
            dependencies {
                api "org.jetbrains.kotlinx:multik-core:0.2.0"
                api "org.jetbrains.kotlinx:multik-default:0.2.0"
                api 'com.microsoft.onnxruntime:onnxruntime:1.16.0'
                api 'io.github.microutils:kotlin-logging:2.1.21' // for logging
            }
        }
        jvmTest {
            dependencies {
                implementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
                implementation 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
                implementation 'org.junit.jupiter:junit-jupiter-params:5.11.4'
                runtimeOnly 'org.junit.platform:junit-platform-launcher'
                implementation project(":api")
                implementation project(":dataset")
            }
        }
        androidMain {
            dependencies {
                api 'com.microsoft.onnxruntime:onnxruntime-android:1.16.0'
                api 'androidx.camera:camera-core:1.6.1'
            }
        }
    }
    explicitApiWarning()
}

tasks.named('jvmTest') {
    useJUnitPlatform()
}
